# Generated by Django 5.2.1 on 2025-06-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(verbose_name="Время окончания"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipient",
            field=models.ManyToManyField(
                to="mailing.recipient", verbose_name="Получатели"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(verbose_name="Время начала"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Cоздана"),
                    ("started", "Запущена"),
                    ("ended", "Завершена"),
                ],
                default="created",
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("fail", "Не успешно")],
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "answer_post_server",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
