# Generated by Django 5.2 on 2025-06-20 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_attempt_owner_mailing_owner_message_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
    ]
