# Generated by Django 5.2 on 2025-06-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={"verbose_name": "Попытка", "verbose_name_plural": "Попытки"},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_blocked", "Может блокировать")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "verbose_name": "Получатель-клиент",
                "verbose_name_plural": "Получатели-клиенты",
            },
        ),
    ]
