# Generated by Django 5.2 on 2025-06-26 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_attempt_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания",
            ),
            preserve_default=False,
        ),
    ]
