# Generated by Django 5.2 on 2025-06-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_mailing_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Cоздана"),
                    ("started", "Запущена"),
                    ("ended", "Завершена"),
                    ("stopped", "Остановлена вручную"),
                ],
                default="created",
                verbose_name="Статус рассылки",
            ),
        ),
    ]
