# Generated by Django 5.2 on 2025-05-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogrecord",
            options={
                "ordering": ["title", "content", "created_at", "publication"],
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
            },
        ),
        migrations.AlterField(
            model_name="blogrecord",
            name="number_of_views",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Количество просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="blogrecord",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/images", verbose_name="Превью"
            ),
        ),
    ]
