# Generated by Django 5.2 on 2025-06-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogrecord_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogrecord",
            name="publication",
            field=models.BooleanField(default=True, verbose_name="Признак публикации"),
        ),
    ]
