# Generated by Django 5.2 on 2025-06-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
